<a href="https://colab.research.google.com/github/mitparekh8263/CV-2026-H11/blob/main/Practical_02/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import cv2
import matplotlib.pyplot as plt

In [ ]:
img = cv2.imread('/content/tiger.jpg', cv2.IMREAD_GRAYSCALE)
img.shape

In [ ]:
plt.imshow(img, cmap='gray')
plt.show()

let img matrix of 5 * 5 be:

[
  
  [120 123 125 128 130]

  [122 124 126 129 131]

  [125 127 180 132 137]

  [128 130 133 135 137]

  [131 133 135 138 140]

]

In [ ]:
def add_salt_pepper_noise(img, prob = 0.3) : # default val = 0.3
  noisy_img = img.copy()

  random = np.random.rand(*img.shape) # * used to pass the shape parameter in random funcn
  noisy_img[random < prob/2] = 0
  noisy_img[random > 1 - prob/2] = 255

  return noisy_img

let random no generated b/w 0, 1:

[

[0.40 0.08 0.55 0.92 0.30]

[0.45 0.12 0.76 0.35 0.95]

[0.60 0.03 0.50 0.88 0.25]

[0.70 0.15 0.91 0.33 0.65]

[0.05 0.80 0.22 0.94 0.50]

]

we choose (prob / 2) and (1 - (prob / 2)) because the sum results the total probability i.e. 1 and prob of salt and pepper noise also remains same

prob = 0.2 => prob / 2 = 0.1 & 1 - (prob / 2) = 0.9

if random < 0.1 then img[random_no] = 0 => img[0.08], img[0.03], img[0.05] = 0 i.e. black pepper noise

if random > 0.9 then img[random_no] = 255 => img[0.92], img[0.95], img[0.91], img[0.94] = 255 i.e. white salt noise


In [ ]:
prob = 0.2

noisy_img = add_salt_pepper_noise(img, prob)
plt.imshow(noisy_img, cmap='gray')
plt.show()

so resultant noisy img matrix becomes:

[

[120 0 125 255 130]

[122 124 126 129 255]

[125 0 180 132 137]

[128 130 255 135 137]

[0 133 135 255 140]

]

In [ ]:
def remove_salt_pepper_noise(img) :
  clean_img = img.copy()
  row, col = img.shape

  for i in range(2, row-2) :
    for j in range(2, col-2) :
      window = img[i-2:i+3, j-2:j+3] # 5*5 window size
      clean_img[i, j] = np.median(window)

  return clean_img

to remove the noise we must use the median method of numpy library and first of all we select the 5 * 5 window (row from 0 to 4 and col from 0 to 4) i.e. neighbourhood matrix around a pixel of image and we must select odd*odd window size to get exact center pixel element

here center pixel is img[2,2] = 180

convert 2D matrix into 1D array:

[120 0 125 255 130 122 124 126 129 255 125 127 **180** 132 137 128 130 255 135 137 0 133 135 255 140]

sort them:

[0 0 120 122 124 125 125 126 127 128 129 130 **130** 132 133 135 135 137 137 140 180 255 255 255 255]

extract the median ((25 + 1) / 2 = 13) pixel value i.e list[13] = 130

so change img[2,2] pixel val from 180 to 130 and convert the array back to matrix

In [ ]:
clean_img = remove_salt_pepper_noise(noisy_img)
plt.imshow(clean_img, cmap='gray')
plt.show()

so final clean img matrix:

[

[120 0 125 255 130]

[122 124 126 129 255]

[125 0 **130** 132 137]

[128 130 255 135 137]

[0 133 135 255 140]

]

but the anomaly is that as much we increase the window size from 5 * 5 to 7 * 7 and so on then we clean the noise more but the image clarity decreses i.e. it becomes more blur